---
application:
  name: "turbo-test"
  project: "ghost-project"
  organization: "QoveryCommunity"
routers:
- name: "main-turbo-test"
  routes:
  - application_name: "turbo-test"
    paths:
    - "/*"
