---
application:
  name: "devfullstack-ghost"
  project: "ghost-project"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "studi"
  version: "8.0"
- type: "POSTGRESQL"
  name: "studifull"
  version: "11"
routers:
- name: "main-devfullstack-ghost"
  routes:
  - application_name: "devfullstack-ghost"
    paths:
    - "/*"
